const Endpoints = {
    authorize: '/api/Authen',
    me: '/api/Authen/me',
    users: '/api/User',
    customers: '/api/User/user',
    infos: (username) => `/api/User/user/${username}`,
    changePassword: '/api/User/password',
    disable: '/api/User/disable',
    disableId: (id) => `/api/User/disable/${id}`,
    usersId: (staffCode) => `/api/User/${staffCode}`,
    realEstates: (username) => `/RealEstate/name=${username}`,
    realEstatesId: (realEstateID) => `/RealEstate/${realEstateID}`,
    categories: `/Category`,
    categoriesId: (categoryID) => `/Category/${categoryID}`,
    newsName: (username) => `/News/name=${username}`,
    news: '/News',
    newsId: (newsID) => `/News/${newsID}`,
    disableNewsId: (id) => `/News/disable/${id}`,
    orders: '/RealEstate/Order',
    ordersId: (orderID) => `/RealEstate/id=${orderID}`,
    reports:(username) => `/Report/name=${username}`,
    authentication: '/api/Authen',
};

export default Endpoints;
